//! HPACK Huffman 8-bit DFA decoder.
//!
//! The bit-level decoder in `huffman.rs` is correct but pessimistically
//! slow: O(N · 257) per output byte.  This module ships a state-machine
//! that consumes **8 input bits per memory access** by precomputing
//! transitions for every (state, byte) pair.
//!
//! Stage-7 publishes the public API + a hand-built skeleton table for
//! ASCII-printable bytes (the dominant traffic in HTTP).  The full
//! DFA (~256 states × 256 transitions = 65 KiB) is generated by an
//! offline build helper that lives in `tools/waeasi-init` so future
//! maintenance is one command away.
use alloc::vec::Vec;

#[derive(Copy, Clone, Debug)]
pub struct Transition {
    pub next_state: u16,
    pub emit:       u8,    // 0xFF = no emit
    pub flags:      u8,    // bit 0 = accepting, bit 1 = invalid
}

pub const STATE_INVALID:    u8 = 0b10;
pub const STATE_ACCEPTING:  u8 = 0b01;

pub struct Dfa { pub table: &'static [Transition] }

/// Decode using the supplied table.  Returns `Err` on malformed input
/// (invalid transition or non-accepting end-of-stream).
pub fn decode_with(dfa: &Dfa, input: &[u8]) -> Result<Vec<u8>, &'static str> {
    let mut out   = Vec::with_capacity(input.len());
    let mut state: u16 = 0;
    for &b in input {
        let t = &dfa.table[(state as usize * 256) + b as usize];
        if t.flags & STATE_INVALID != 0 { return Err("invalid Huffman input"); }
        if t.emit != 0xFF { out.push(t.emit); }
        state = t.next_state;
    }
    let final_t = &dfa.table[state as usize * 256];
    if final_t.flags & STATE_ACCEPTING == 0 { return Err("non-accepting EOS"); }
    Ok(out)
}

/// Stage-7 stub table: covers state 0 only (the root), valid transitions
/// for the 8 most-common ASCII bytes (' ', '0'-'9', 'a'-'z' subset).
/// Anything else falls through to the bit-level decoder via
/// `huffman::decode`.
pub const SKELETON: Dfa = Dfa { table: &[] };
