//! Tiny TOML-subset parser/emitter for `waeasi.toml`.
//!
//! Same shape as `components/manifest/parse.rs` (kernel side) so the
//! kernel and the builder agree on the schema.  Values supported:
//! `string`, `int`, `bool`, `array<string>`.  Sections: `[component]`,
//! `[capabilities]`, `[resources]`, `[exports]`.

use std::path::Path;

use crate::error::{BuildError, Result};
use crate::fs;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum World { Handler, Scheduled, Stream }

impl World {
    fn from_str(s: &str) -> Result<Self> {
        match s {
            "handler"   => Ok(World::Handler),
            "scheduled" => Ok(World::Scheduled),
            "stream"    => Ok(World::Stream),
            o => Err(BuildError::Manifest(format!("unknown world: {o}"))),
        }
    }
    pub fn as_str(&self) -> &'static str {
        match self {
            World::Handler => "handler",
            World::Scheduled => "scheduled",
            World::Stream => "stream",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Right {
    FsRead, FsWrite, NetConnect, NetBind,
    ClockWall, ClockMono, RandomInsec, RandomSec,
}

impl Right {
    fn from_str(s: &str) -> Result<Self> {
        Ok(match s {
            "FS_READ"      => Right::FsRead,
            "FS_WRITE"     => Right::FsWrite,
            "NET_CONNECT"  => Right::NetConnect,
            "NET_BIND"     => Right::NetBind,
            "CLOCK_WALL"   => Right::ClockWall,
            "CLOCK_MONO"   => Right::ClockMono,
            "RANDOM_INSEC" => Right::RandomInsec,
            "RANDOM_SEC"   => Right::RandomSec,
            o => return Err(BuildError::Manifest(format!("unknown right: {o}"))),
        })
    }
    pub fn as_str(&self) -> &'static str {
        match self {
            Right::FsRead => "FS_READ", Right::FsWrite => "FS_WRITE",
            Right::NetConnect => "NET_CONNECT", Right::NetBind => "NET_BIND",
            Right::ClockWall => "CLOCK_WALL", Right::ClockMono => "CLOCK_MONO",
            Right::RandomInsec => "RANDOM_INSEC", Right::RandomSec => "RANDOM_SEC",
        }
    }
}

#[derive(Debug, Clone, Default)]
pub struct ManifestSpec {
    pub name: String,
    pub version: String,
    pub world: Option<World>,
    pub rights: Vec<Right>,
    pub cpu_shares: Option<u32>,
    pub memory_pages_max: Option<u32>,
    pub linear_mem_max: Option<String>,
    pub exports: Vec<(String, String)>,
}

#[derive(Debug, Clone)]
pub struct Manifest { pub spec: ManifestSpec }

impl Manifest {
    pub fn from_path(path: &Path) -> Result<Self> {
        let text = fs::read_text(path)?;
        Self::parse(&text)
    }

    pub fn parse(text: &str) -> Result<Self> {
        let mut s = ManifestSpec::default();
        let mut section = String::new();
        for raw in text.lines() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') { continue; }
            if let Some(rest) = line.strip_prefix('[').and_then(|x| x.strip_suffix(']')) {
                section = rest.to_string();
                continue;
            }
            let (k, v) = line.split_once('=').ok_or_else(||
                BuildError::Manifest(format!("bad line: {line}"))
            )?;
            assign(&mut s, &section, k.trim(), v.trim())?;
        }
        if s.name.is_empty() || s.version.is_empty() {
            return Err(BuildError::Manifest("name/version required".into()));
        }
        Ok(Manifest { spec: s })
    }

    pub fn render(&self, user_digest: &str, engine_digest: Option<&str>, sdk: &str) -> String {
        let s = &self.spec;
        let mut out = String::new();
        out.push_str("# Generated by waeasi-builder — do not hand-edit\n\n");
        out.push_str("[component]\n");
        out.push_str(&format!("name    = \"{}\"\n", s.name));
        out.push_str(&format!("version = \"{}\"\n", s.version));
        out.push_str(&format!("digest  = \"sha256:{user_digest}\"\n"));
        if let Some(eng) = engine_digest {
            out.push_str(&format!("engine  = \"sha256:{eng}\"\n"));
        }
        if let Some(w) = &s.world {
            out.push_str(&format!("world   = \"{}\"\n", w.as_str()));
        }
        out.push_str(&format!("sdk     = \"{sdk}\"\n\n"));
        out.push_str("[capabilities]\nrights = [");
        for (i, r) in s.rights.iter().enumerate() {
            if i > 0 { out.push_str(", "); }
            out.push_str(&format!("\"{}\"", r.as_str()));
        }
        out.push_str("]\n\n");
        out.push_str("[resources]\n");
        if let Some(c) = s.cpu_shares       { out.push_str(&format!("cpu_shares       = {c}\n")); }
        if let Some(m) = s.memory_pages_max { out.push_str(&format!("memory_pages_max = {m}\n")); }
        if let Some(l) = &s.linear_mem_max  { out.push_str(&format!("linear_mem_max   = \"{l}\"\n")); }
        if !s.exports.is_empty() {
            out.push_str("\n[exports]\n");
            for (k, v) in &s.exports { out.push_str(&format!("{k} = \"{v}\"\n")); }
        }
        out
    }
}

fn assign(s: &mut ManifestSpec, section: &str, k: &str, v: &str) -> Result<()> {
    match section {
        "component" => match k {
            "name"    => s.name    = strip_str(v)?.into(),
            "version" => s.version = strip_str(v)?.into(),
            "world"   => s.world   = Some(World::from_str(strip_str(v)?)?),
            "digest" | "engine" | "sdk" => { /* informational only */ }
            _ => return Err(BuildError::Manifest(format!("bad key: {k}"))),
        },
        "capabilities" => if k == "rights" {
            s.rights = parse_str_array(v)?
                .iter().map(|x| Right::from_str(x)).collect::<Result<_>>()?;
        } else { return Err(BuildError::Manifest(format!("bad key: {k}"))); },
        "resources" => match k {
            "cpu_shares" => s.cpu_shares = Some(v.parse().map_err(|_|
                BuildError::Manifest("cpu_shares not an int".into()))?),
            "memory_pages_max" => s.memory_pages_max = Some(v.parse().map_err(|_|
                BuildError::Manifest("memory_pages_max not an int".into()))?),
            "linear_mem_max" => s.linear_mem_max = Some(strip_str(v)?.into()),
            _ => return Err(BuildError::Manifest(format!("bad key: {k}"))),
        },
        "exports" => s.exports.push((k.into(), strip_str(v)?.into())),
        o => return Err(BuildError::Manifest(format!("unknown section: {o}"))),
    }
    Ok(())
}

fn strip_str(v: &str) -> Result<&str> {
    let v = v.trim();
    if v.len() >= 2 && v.starts_with('"') && v.ends_with('"') { Ok(&v[1..v.len()-1]) }
    else { Err(BuildError::Manifest(format!("expected string: {v}"))) }
}

fn parse_str_array(v: &str) -> Result<Vec<String>> {
    let v = v.trim();
    let inner = v.strip_prefix('[').and_then(|x| x.strip_suffix(']'))
        .ok_or_else(|| BuildError::Manifest(format!("expected array: {v}")))?;
    let mut out = Vec::new();
    for tok in inner.split(',') {
        let t = tok.trim();
        if t.is_empty() { continue; }
        out.push(strip_str(t)?.into());
    }
    Ok(out)
}
