//! Component-scaffold templates.
use std::fs;
use std::path::PathBuf;

pub fn scaffold(name: &str) -> Result<PathBuf, String> {
    let root = PathBuf::from("components").join(name);
    if root.exists() { return Err(format!("{:?} already exists", root)); }
    fs::create_dir_all(root.join("src")).map_err(|e| format!("mkdir: {}", e))?;

    fs::write(root.join("Cargo.toml"),    cargo_toml(name)).map_err(io_err)?;
    fs::write(root.join("src/lib.rs"),    lib_rs(name)).map_err(io_err)?;
    fs::write(root.join("manifest.toml"), manifest_toml(name)).map_err(io_err)?;
    Ok(root)
}

fn io_err(e: std::io::Error) -> String { format!("write: {}", e) }

fn cargo_toml(name: &str) -> String {
    format!(r#"[package]
name        = "{}"
description = "WAeasi component — generated by waeasi-init"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
"#, name)
}

fn lib_rs(name: &str) -> String {
    format!(r#"//! `{name}` — WAeasi Wasm component.
//!
//! Imports a minimal WASI Preview-2 surface; entry point is `_start`.
//! Customize the body in `entry::run`.
#![no_std]

#[cfg(target_arch = "wasm32")]
mod entry {{
    extern "C" {{
        fn wasi_clocks_now_ns() -> u64;
        fn wasi_io_write(fd: u32, ptr: *const u8, len: usize) -> usize;
    }}
    const STDOUT: u32 = 1;
    const HELLO: &[u8] = b"hello from {name}\n";

    #[unsafe(no_mangle)]
    pub extern "C" fn _start() {{
        unsafe {{ wasi_io_write(STDOUT, HELLO.as_ptr(), HELLO.len()); }}
        let _ = unsafe {{ wasi_clocks_now_ns() }};
    }}
}}

#[cfg(target_arch = "wasm32")]
#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {{ loop {{}} }}
"#, name = name)
}

fn manifest_toml(name: &str) -> String {
    format!(r#"[component]
name    = "{}"
version = "0.1.0"

[capabilities]
rights = ["CLOCK_MONO"]

[resources]
cpu_shares       = 100
memory_pages_max = 16
linear_mem_max   = "1 MiB"
"#, name)
}
